In [1]:
from pysus.ftp.databases.sia import SIA
from pysus.ftp.databases.sih import SIH
from pysus.ftp.databases.cnes import CNES
from pysus.ftp.databases.sim import SIM
from pysus.ftp.databases.sinasc import SINASC
from pysus.ftp.databases.sinan import SINAN
import pandas as pd
import os

sia = SIA().load()
sih = SIH().load()
cnes = CNES().load()
sim = SIM().load()
sinasc = SINASC().load()
sinan = SINAN().load()

In [3]:
cnes.groups
files = cnes.get_files("PF", uf=["RJ"], year=2024, month=1)
parquet_cnes = cnes.download(files, local_dir="pysus_sih/Analises/CNES/PF")

100%|██████████| 25.2M/25.2M [00:00<00:00, 16.2GB/s]

In [6]:
caminho_cnes = '/root/pysus_sih/Analises/pysus_sih/Analises/CNES/PF/PFRJ2401.parquet/0b0f748d66d44ce2a58df292e1241287-0.parquet'
df_temp = pd.read_parquet(caminho_cnes)
df_temp

,CNES,CODUFMUN,REGSAUDE,MICR_REG,DISTRSAN,DISTRADM,TPGESTAO,PF_PJ,CPF_CNPJ,NIV_DEP,...,VINCUL_A,VINCUL_N,PROF_SUS,PROFNSUS,HORAOUTR,HORAHOSP,HORA_AMB,COMPETEN,UFMUNRES,NAT_JUR
0,2274698,330510,330,,,,M,3,00000000000000,3,...,0,0,1,0,0,0,40,202401,000000,1244
1,2274698,330510,330,,,,M,3,00000000000000,3,...,0,0,1,0,0,0,40,202401,000000,1244
2,2274698,330510,330,,,,M,3,00000000000000,3,...,0,0,1,0,0,0,40,202401,000000,1244
3,2274698,330510,330,,,,M,3,00000000000000,3,...,0,0,1,0,0,0,40,202401,000000,1244
4,2274698,330510,330,,,,M,3,00000000000000,3,...,0,0,1,0,0,0,40,202401,000000,1244
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,0025143,330630,,,02,,M,3,03272699000137,1,...,1,0,1,0,44,0,0,202401,000000,1031
29996,0025143,330630,,,02,,M,3,03272699000137,1,...,1,0,1,0,0,22,22,202401,000000,1031
29997,0025143,330630,,,02,,M,3,03272699000137,1,...,1,0,1,0,0,22,22,202401,000000,1031
29998,0025143,330630,,,02,,M,3,03272699000137,1,...,1,0,1,0,40,0,0,202401,000000,1031
29999,0025143,330630,,,02,,M,3,03272699000137,1,...,0,0,1,0,0,24,24,202401,000000,1031

In [5]:
sia

sia.metadata

{'long_name': 'Sistema de Informações Ambulatoriais',
 'source': 'http://sia.datasus.gov.br/principal/index.php',
 'description': 'O Sistema de Informação Ambulatorial (SIA) foi instituído pela Portaria GM/MS n.º 896 de 29 de junho de 1990. Originalmente, o SIA foi concebido a partir do projeto SICAPS (Sistema de Informação e Controle Ambulatorial da Previdência Social), em que os conceitos, os objetivos e as diretrizes criados para o desenvolvimento do SICAPS foram extremamente importantes e amplamente utilizados para o desenvolvimento do SIA, tais como: (i) o acompanhamento das programações físicas e orçamentárias; (ii) o acompanhamento das ações de saúde produzidas; (iii) a agilização do pagamento e controle orçamentário e financeiro; e (iv) a formação de banco de dados para contribuir com a construção do SUS.'}

In [6]:
sia.groups

{'AB': 'APAC de Cirurgia Bariátrica',
 'ABO': 'APAC de Acompanhamento Pós Cirurgia Bariátrica',
 'ACF': 'APAC de Confecção de Fístula',
 'AD': 'APAC de Laudos Diversos',
 'AM': 'APAC de Medicamentos',
 'AMP': 'APAC de Acompanhamento Multiprofissional',
 'AN': 'APAC de Nefrologia',
 'AQ': 'APAC de Quimioterapia',
 'AR': 'APAC de Radioterapia',
 'ATD': 'APAC de Tratamento Dialítico',
 'BI': 'Boletim de Produção Ambulatorial individualizado',
 'IMPBO': '',
 'PA': 'Produção Ambulatorial',
 'PAM': '',
 'PAR': '',
 'PAS': '',
 'PS': 'RAAS Psicossocial',
 'SAD': 'RAAS de Atenção Domiciliar'}

In [2]:
estados = [
    "AC",  "AL",  "AP",  "AM",  
    "BA",  "CE",  "DF",   "ES",   "GO",  
    "MA",  "MT",   "MS",   "MG",  
    "PA",  "PB",  "PR", 
    "PE",  "PI",  "RJ",   "RN",   "RS",   
    "RO",  "RR",  "SC",   
    "SP",  
    "SE",  "TO"   
]
anos = [
    #1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 
        2024
        ]

In [5]:
#files_SP = sia.get_files("PA", uf=["SP"], year=[2018, 2019, 2020, 2021, 2022, 2023, 2024])
#files_PR = sia.get_files("PA", uf=["PR"], year=[2022, 2023, 2024])
files_MG = sia.get_files("PA", uf=estados, year=[2024], month=[10,11,12])

In [4]:
files_MG = sia.get_files("PA", uf=estados, year=[2024], month=[10,11,12])

parquet = sia.download(files_MG, local_dir="pysus_sih/parquet_files/SIA/PA")

PARJ2411a.parquet:   4%|▎         | 360k/9.98M [04:21<4:11:34, 637B/s]

:

In [6]:
#parquet = sia.download(files_SP, local_dir="pysus_sih/parquet_files/SIA/PA")
#parquet = sia.download(files_PR, local_dir="pysus_sih/parquet_files/SIA/PA")
parquet = sia.download(files_MG, local_dir="pysus_sih/parquet_files/SIA/PA")

PARJ2410a.parquet:   3%|▎         | 330k/10.4M [00:54<47:34, 3.54kB/s]

:

In [ ]:
Grupos = ['PA']

for Grupo in Grupos:
    try:
        # Obtém os arquivos para o grupo atual
        print(f"Processando o grupo: {Grupo}")
        files = sia.get_files([Grupo], uf=estados, year=anos)
        # Faz o download dos arquivos para o diretório especificado
        local_dir = f"pysus_sih/parquet_files/SIA/{Grupo}"
        parquet = sia.download(files, local_dir=local_dir)
        
        print(f"Arquivos para o grupo '{Grupo}' baixados com sucesso em: {local_dir}")
    except Exception as e:
        print(f"Erro ao processar o grupo '{Grupo}': {e}")

Processando o grupo: PA

PAAC0001.dbc:   0%|          | 0.00/79.6k [00:00<?, ?B/s]

PAAC0001.parquet:   0%|          | 0.00/4.65k [00:00<?, ?B/s]     /root/pysus_sih/venv/lib/python3.10/site-packages/tqdm/std.py:533: TqdmWarning: clamping frac to range [0, 1]
  full_bar = Bar(frac,
PAAC1012.parquet:   0%|          | 0.00/61.7k [00:00<?, ?B/s]

In [32]:
caminho_erro = 'pysus_sih/parquet_files/SIH/SP/SPAC9708.parquet/e66a285d426e4032b5dfb58f9a2fa2f0-0.parquet'
df_temp = pd.read_parquet(caminho_erro)
df_temp

,SP_GESTOR,SP_UF,SP_AA,SP_MM,SP_CNES,SP_NAIH,SP_PROCREA,SP_DTINTER,SP_DTSAIDA,SP_NUM_PR,SP_TIPO,SP_CPFCGC,SP_ATOPROF,SP_TP_ATO,SP_QTD_ATO,SP_PTSP,SP_NF,SP_VALATO
0,350000,35,2007,02,2080672,3507106573180,82500061,20070214,20070218,00041001,03,00000002080672,17064040,15,1,8,000000,0.69
1,350000,35,2007,02,2080672,3507106573180,82500061,20070214,20070218,00041001,03,00000002080672,21003068,16,1,44,000000,3.81
2,350000,35,2007,02,2080672,3507106573180,82500061,20070214,20070218,00041001,03,00000002080672,04001010,18,2,50,000000,4.33
3,350000,35,2007,02,2080672,3507106573212,77500024,20070214,20070221,00041001,45,00000069367841,25001019,07,1,18,000000,12.05
4,350000,35,2007,02,2080672,3507106573212,77500024,20070214,20070221,00041001,45,00004339748854,25001019,07,7,126,000000,84.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1486024,355030,35,2007,02,2081970,3507102736973,40060012,20061208,20070104,00041001,03,00000002081970,17042046,15,1,8,000000,4.01
1486025,355030,35,2007,02,2081970,3507102736973,40060012,20061208,20070104,00041001,03,00000002081970,17064040,15,1,8,000000,4.01
1486026,355030,35,2007,02,2081970,3507102736973,40060012,20061208,20070104,00041001,03,00000002081970,17023041,15,1,8,000000,4.01
1486027,355030,35,2007,02,2081970,3507102736973,40060012,20061208,20070104,00041001,03,00000002081970,17059046,15,1,8,000000,4.01
1486028,355030,35,2007,02,2081970,3507102736973,40060012,20061208,20070104,00041001,03,00000002081970,17055040,15,1,8,000000,4.01

In [ ]:
# colunas = df.columns #RD
# with open('colunas_rj.txt', 'w') as arquivo:
#     # Escrever cada nome de coluna em uma nova linha
#     for coluna in colunas:
#         arquivo.write(f"{coluna}\n")

In [ ]:
df = pd.read_parquet("parquet_files/SIH/SP/SPSP1801.parquet")
print(df.columns)

FileNotFoundError: [Errno 2] No such file or directory: 'parquet_files/SIH/SP/SPSP1801.parquet'

In [13]:
# 1. Informações Gerais sobre o DataFrame
print("Informações do DataFrame:")
print(df.info())

Informações do DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62568 entries, 0 to 62567
Data columns (total 36 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SP_GESTOR   62568 non-null  object
 1   SP_UF       62568 non-null  object
 2   SP_AA       62568 non-null  object
 3   SP_MM       62568 non-null  object
 4   SP_CNES     62568 non-null  object
 5   SP_NAIH     62568 non-null  object
 6   SP_PROCREA  62568 non-null  object
 7   SP_DTINTER  62568 non-null  object
 8   SP_DTSAIDA  62568 non-null  object
 9   SP_NUM_PR   62568 non-null  object
 10  SP_TIPO     62568 non-null  object
 11  SP_CPFCGC   62568 non-null  object
 12  SP_ATOPROF  62568 non-null  object
 13  SP_TP_ATO   62568 non-null  object
 14  SP_QTD_ATO  62568 non-null  object
 15  SP_PTSP     62568 non-null  object
 16  SP_NF       62568 non-null  object
 17  SP_VALATO   62568 non-null  object
 18  SP_M_HOSP   62568 non-null  object
 19  SP_M_PAC    62568 non-null  object
 20  SP_DES_HOS  62568 non-null  object
 21  SP_DES_PAC  62568 non-null  object
 22  SP_COMPLEX  62568 non-null  object
 23  SP_FINANC   62568 non-null  object
 24  SP_CO_FAEC  62568 non-null  object
 25  SP_PF_CBO   62568 non-null  object
 26  SP_PF_DOC   62568 non-null  object
 27  SP_PJ_DOC   62568 non-null  object
 28  IN_TP_VAL   62568 non-null  object
 29  SEQUENCIA   62568 non-null  object
 30  REMESSA     62568 non-null  object
 31  SERV_CLA    62568 non-null  object
 32  SP_CIDPRI   62568 non-null  object
 33  SP_CIDSEC   62568 non-null  object
 34  SP_QT_PROC  62568 non-null  object
 35  SP_U_AIH    62568 non-null  object
dtypes: object(36)
memory usage: 17.2+ MB
None

In [14]:
# 2. Estatísticas Descritivas de Colunas Numéricas
print("\nEstatísticas Descritivas (Numéricas):")
print(df.describe())

Estatísticas Descritivas (Numéricas):
       SP_GESTOR  SP_UF  SP_AA  SP_MM  SP_CNES        SP_NAIH  SP_PROCREA  \
count      62568  62568  62568  62568    62568          62568       62568
unique         1      1      1      1       24           5266         379
top       120000     12   2023     03  2001578  1223100144387  0411010034
freq       62568  62568  62568  62568    13635            164        6390

       SP_DTINTER SP_DTSAIDA SP_NUM_PR  ...        SP_PF_DOC       SP_PJ_DOC  \
count       62568      62568     62568  ...            62568           62568
unique        175        157         1  ...              698              39
top      20230228   20230303            ...  000000000000000  00000002001578
freq         1390       1444     62568  ...            44818           12643

       IN_TP_VAL  SEQUENCIA                REMESSA SERV_CLA SP_CIDPRI  \
count      62568      62568                  62568    62568     62568
unique         2       5266                      1       24      1062
top            1       4360  HE12000001N202303.DTS   000000      O800
freq       48367        164                  62568    59215      4779

       SP_CIDSEC SP_QT_PROC SP_U_AIH
count      62568      62568    62568
unique         1         78        2
top         0000          1        0
freq       62568      35777    57302

[4 rows x 36 columns]

In [15]:
# 3. Estatísticas Descritivas de Colunas Categóricas
print("\nEstatísticas Descritivas (Categóricas):")
print(df.describe(include=['object', 'category']))

Estatísticas Descritivas (Categóricas):
       SP_GESTOR  SP_UF  SP_AA  SP_MM  SP_CNES        SP_NAIH  SP_PROCREA  \
count      62568  62568  62568  62568    62568          62568       62568
unique         1      1      1      1       24           5266         379
top       120000     12   2023     03  2001578  1223100144387  0411010034
freq       62568  62568  62568  62568    13635            164        6390

       SP_DTINTER SP_DTSAIDA SP_NUM_PR  ...        SP_PF_DOC       SP_PJ_DOC  \
count       62568      62568     62568  ...            62568           62568
unique        175        157         1  ...              698              39
top      20230228   20230303            ...  000000000000000  00000002001578
freq         1390       1444     62568  ...            44818           12643

       IN_TP_VAL  SEQUENCIA                REMESSA SERV_CLA SP_CIDPRI  \
count      62568      62568                  62568    62568     62568
unique         2       5266                      1       24      1062
top            1       4360  HE12000001N202303.DTS   000000      O800
freq       48367        164                  62568    59215      4779

       SP_CIDSEC SP_QT_PROC SP_U_AIH
count      62568      62568    62568
unique         1         78        2
top         0000          1        0
freq       62568      35777    57302

[4 rows x 36 columns]

In [3]:
caminho_cnes = '/root/pysus_sih/parquet_files/SIA/PA/PARJ2210b.parquet/1d448d576ff04e8296e574b2e236d264-0.parquet'
df_temp = pd.read_parquet(caminho_cnes)

# Filtrando apenas as colunas especificadas
colunas_selecionadas = [col for col in ['PA_CODUNI', 'PA_GESTAO', 'PA_MVM', 'PA_PROC_ID', 'PA_DOCORIG',
                                       'PA_SEXO', 'PA_QTDPRO', 'PA_QTDAPR', 'PA_VALPRO', 'PA_VALAPR',
                                       'PA_VL_CF', 'PA_VL_CL', 'PA_VL_INC'] if col in df_temp.columns]

df_temp = df_temp[colunas_selecionadas]
df_temp

,PA_CODUNI,PA_GESTAO,PA_MVM,PA_PROC_ID,PA_DOCORIG,PA_SEXO,PA_QTDPRO,PA_QTDAPR,PA_VALPRO,PA_VALAPR,PA_VL_CF,PA_VL_CL,PA_VL_INC
0,9210806,330285,202210,0203010086,I,F,1,1,14.37,14.37,0.00,0.00,0.00
1,3111156,330285,202210,0205010032,I,M,1,0,67.86,0.00,0.00,0.00,0.00
2,3111156,330285,202210,0204030188,I,F,1,1,45.00,45.00,0.00,0.00,0.00
3,6681298,330285,202210,0205020186,I,F,1,1,24.20,24.20,0.00,0.00,0.00
4,6683444,330285,202210,0302050027,I,M,1,1,4.67,4.67,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,5371120,330170,202210,0803010125,I,M,4,4,19.80,19.80,0.00,0.00,0.00
29996,5371120,330170,202210,0803010125,I,F,4,4,19.80,19.80,0.00,0.00,0.00
29997,2290227,330170,202210,0206020031,I,M,1,1,136.41,136.41,0.00,0.00,0.00
29998,2290227,330170,202210,0206010079,I,F,1,1,97.44,97.44,0.00,0.00,0.00
29999,2290227,330170,202210,0206030037,I,F,1,1,138.63,138.63,0.00,0.00,0.00